# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh"

  #config.vm.provision "file", 
  #  source: "./cloudera-transparent_hugepage.sh", 
  #  destination: "/etc/profile.d/"

  # config.vm.provision "shell",
  #   inline: "mv /tmp/cloudera-transparent_hugepage.sh /root/"

  config.vm.provision "bootstrap", type:"ansible" do |ansible|
    ansible.playbook = "bootstrap.yml"
  end

  # Cloudera Master Server
  config.vm.define "master.cloudera" do |c|
    c.vm.hostname = "master.cloudera"
    c.vm.network "private_network", ip: "192.168.0.10"
    c.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "8192"]
    end
  end

  NodeCount = 3

  # Cloudera Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}.cloudera" do |c|
      c.vm.hostname = "node#{i}.cloudera"
      c.vm.network "private_network", ip: "192.168.0.1#{i}"
    end
  end
  
end
